# Accessing FAO ASIS data

In this exercise we download the Vegetation Health Index (VHI) and Agricultural Stress Index (ASI) for an administrative region and identify the specific areas most impacted by drought.

More information on ASIS: https://www.fao.org/giews/earthobservation/index.jsp?lang=en

<div class="alert alert-block alert-warning">
<b>Running this notebook on CDSE notebooks?</b><br>

Make sure you select the Geo science python kernel.<br>

Execute the following cell to install some required python packages.

</div>

In [ ]:
!pip install ipykernel ipyleaflet geopandas geojson --quiet

### Before you start

The following cell ensures a correct download of the data from Google Cloud Storage.

In [2]:
import os
os.environ['GS_NO_SIGN_REQUEST'] = 'YES'

### Step 1: Inspect available ASIS data

Here you get an overview of the available data...

In [1]:
from vito_agri_tutorials.fao.asis import ASIS_SUPPORTED_VARIABLES
import pandas as pd

df_vars = pd.DataFrame.from_dict(ASIS_SUPPORTED_VARIABLES, orient='index', columns=['Description'])
df_vars

                                    Description
VCI-D      Vegetation Condition Index - Dekadal
VCI-M      Vegetation Condition Index - Monthly
VHI-D         Vegetation Health Index - Dekadal
VHI-M        Vegetation Health Index - Monthly
MVHI-D   Mean Vegetation Health Index - Dekadal
MVHI-A  Mean Vegetation Health Index - Seasonal
ASI-D       Agricultural Stress Index - Dekadal
ASI-A      Agricultural Stress Index - Seasonal
DI-D                Drought Intensity - Dekadal
DI-A               Drought Intensity - Seasonal
PHE                           Phenology - Fixed
POS                          Progress of season

### Step 2: Select your administrative region

Using this widget, you can select an administrave region from a list of available regions in a country.<br>

- Select a country first.<br>
- Then select a state from the list of states in the selected country.<br>
- Hit the `Add to selection` button to add the selected state to your selection.<br>

Select one or two states from one country and add them to your selection.<br>

In [3]:
from vito_agri_tutorials.utils.map import RegionPicker

region_picker = RegionPicker()

VBox(children=(Dropdown(description='Country:', layout=Layout(visibility='visible'), options=('Select Country'…

Now we extract the geometries from the selected states:

In [4]:
gdf = region_picker.selection_to_gdf(level=1)
gdf

,ADM1_CODE,id,STR1_YEAR,EXP1_YEAR,STATUS,DISP_AREA,ADM0_CODE,ADM0_NAME,Shape_Leng,Shape_Area,geometry
3333,601,Vlaams Gewest,1000,3000,Member State,NO,27,Belgium,10.825437,1.731443,"MULTIPOLYGON (((4.9259 51.4414, 4.93811 51.444..."

### Step 3: When do the growing seasons take place in your state(s) of interest?

The ASIS portal automatically determines the start and end of up to two growing seasons for each 1 km pixel, based on the long term average (LTA) NDVI time series.<br>
Let's have a look when the growing seasons start and end in your selected state(s):

In [6]:
from pathlib import Path
from vito_agri_tutorials.fao.asis import extract_asis_data

out_dir = Path('./results/2_asis')
out_dir.mkdir(parents=True, exist_ok=True)

variable = "PHE"
# we want start (SOS) and end (EOS) of the growing season
subvariables = ["SOS", "EOS"]
# We want both season 1 and 2
seasons = [1, 2]
landcover = "C"
write_tif = True

for season in seasons:
    for subvariable in subvariables:
        print(f"Extracting {variable}_{subvariable}_season{season}")
        asis_data = extract_asis_data(
            variable,
            gdf,
            out_dir,
            sub_variable=subvariable,
            season=season,
            landcover=landcover,
            write_tif=write_tif,
            debug=True,
        )

Extracting PHE_SOS_season1
Reading file gs://fao-gismgr-asis-data/DATA/ASIS/MAPSET/PHE/ASIS.PHE.GS1.SOS.LC-C.tif
Extracting PHE_EOS_season1
Reading file gs://fao-gismgr-asis-data/DATA/ASIS/MAPSET/PHE/ASIS.PHE.GS1.EOS.LC-C.tif
Extracting PHE_SOS_season2
Reading file gs://fao-gismgr-asis-data/DATA/ASIS/MAPSET/PHE/ASIS.PHE.GS2.SOS.LC-C.tif
Extracting PHE_EOS_season2
Reading file gs://fao-gismgr-asis-data/DATA/ASIS/MAPSET/PHE/ASIS.PHE.GS2.EOS.LC-C.tif

The resulting .tif files were automatically downloaded to your `out_dir`.<br>
You can inspect them in QGIS.<br>
Feel free to use the colormap located in *vito_agri_tutorials/resources/PHE_colormap.clr* for visualization.<br>
(make sure to select Unique/Paletted values before loading the colormap)

**QUESTION**: What do the values in these rasters represent?<br>

**QUESTION**: Why can't you just compute the average start and end of season for the entire state by computing the average value of all pixels?

### Step 4: When was the drought occuring in your selected state(s)?

Now we extract the timeseries of dekadal VHI and ASI indicators and inspect the results visually.<br>
We compute the average VHI and ASI for the entire state(s) and each 10-day period to find out WHEN the drought was really happening.<br>
Feel free to adjust the `start_date` and `end_date` based on your knowledge of the selected regions.

We start with the VHI timeseries:

In [ ]:
from pathlib import Path
from vito_agri_tutorials.fao.asis import extract_asis_data

out_dir = Path('./results/2_asis')
out_dir.mkdir(parents=True, exist_ok=True)

variable = "VHI-D"
start_date = '2022-01-01'
end_date = '2024-12-31'
# No need to specify season or landcover for the VHI data.
season = None
landcover = None
write_tif = True

vhi = extract_asis_data(
    variable,
    gdf,
    out_dir,
    start_date=start_date,
    end_date=end_date,
    season=season,
    landcover=landcover,
    write_tif=write_tif,
    debug=True,)

The .tif files were automatically downloaded to your `out_dir`.<br>
You can inspect them in QGIS. Feel free to use the colormap located in *vito_agri_tutorials/resources/VHI_colormap.txt* for visualization.<br>
(make sure to select Singleband Pseudocolor before loading the colormap)

We now compute the mean VHI over our states for each dekad:<br>

(note that the function below automatically discards any value > 250, which are the "no-data" values in ASIS)

In [ ]:
from vito_agri_tutorials.fao.asis import compute_area_stats, plot_stats

vhi_stats = compute_area_stats(vhi)
vhi_stats = plot_stats(vhi_stats, variable, "mean")
vhi_stats

Now we do the same for the dekadal ASI product:

(make sure you select the same time period as before!)

In [ ]:
from pathlib import Path
from vito_agri_tutorials.fao.asis import extract_asis_data

variable = "ASI-D"
start_date = '2022-01-01'
end_date = '2024-12-31'
# We need to specify a season (1 or 2) and a landcover type (C(ropland) or G(rassland)) for the ASI data:
season = 1
landcover = "C"
write_tif = True

asi = extract_asis_data(
    variable,
    gdf,
    out_dir,
    start_date=start_date,
    end_date=end_date,
    season=season,
    landcover=landcover,
    write_tif=write_tif,
    debug=True,)

The .tif files were automatically downloaded to your `out_dir`.<br>
You can inspect them in QGIS. Feel free to use the colormap located in *vito_agri_tutorials/resources/ASI_colormap.txt* for visualization.<br>
(make sure to select Singleband Pseudocolor before loading the colormap)

Now, we compute area statistics for the selected states and plot the average values across the entire states.

In [ ]:
from vito_agri_tutorials.fao.asis import compute_area_stats, plot_stats

asi_stats = compute_area_stats(asi)
asi_stats = plot_stats(asi_stats, variable, "mean")
asi_stats

Finally, we combine VHI and ASI timeseries in a single plot to ease interpretation.<br>
Upon execution of the next cell, you will be prompted to enter the name of the state for which you want to create the figure.

In [ ]:
import matplotlib.pyplot as plt

state = input("Enter the state name: ")
if state not in vhi_stats.columns:
    print(f"State {state} not found in the dataframe.")
    print(f"Available states: {vhi_stats.columns}")
    raise ValueError(f"State {state} not found in the dataframe.")

# join the two relevant columns of a dataframe
df_vhi_asi = vhi_stats[[state]].join(asi_stats[[state]], lsuffix='_VHI', rsuffix='_ASI')
# rename the columns
df_vhi_asi.columns = ['mean_VHI', 'mean_ASI']

# Plot both variables on same figure
figs, ax1 = plt.subplots(1, figsize=(12, 6))
df_vhi_asi['mean_VHI'].plot(ax=ax1, label='VHI',color='blue')
ax2 = ax1.twinx()
df_vhi_asi['mean_ASI'].plot(ax=ax2, label='ASI',color="orange")

ax1.set_ylabel('Vegetation Health Index [-]')
ax1.legend(loc='upper left', ncol=5)
ax1.set_title('Comparison VHI & ASI time series')

# Set limits for both axes
ax2.set_ylabel('Agricultural Stress Index [%]')
ax2.legend(loc='upper right', ncol=5)

**QUESTION**: Discuss the difference between both curves. Why are there holes in the ASI curve?

**QUESTION**:  Was there a signficant impact of the drought in one of the growing seasons in your selected region?

### Step 5: Where was the drought most severe within the state(s)?

Now let's download the accumulated Vegetation Health Index over the entire growing season (MVHI-A).<br>

This indicator should give you an idea which individual pixels have been most heavily affected across the season.

In [ ]:
from pathlib import Path
from vito_agri_tutorials.fao.asis import extract_asis_data

variable = "MVHI-A"
start_date = '2022-01-01'
end_date = '2024-12-31'
season = 1
landcover = "C"
sub_variable = None
write_tif = True

mvhi = extract_asis_data(
    variable,
    gdf,
    out_dir,
    start_date=start_date,
    end_date=end_date,
    season=season,
    landcover=landcover,
    sub_variable=sub_variable,
    write_tif=write_tif,
    debug=True,)

The .tif files were automatically downloaded to your `out_dir`.<br>
You can inspect them in QGIS. Feel free to use the colormap located in *vito_agri_tutorials/resources/MVHI_colormap.txt* for visualization.<br>
(make sure to select Singleband Pseudocolor before loading the colormap)

### Optional step: Custom integration of VHI over (part of) a (different) growing season

Most crop types are most vulnerable to the impact of drought during the early development stages of their growing cycle. In that sense, it might make sense to only focus on the first half of a particular growing season and compute MVHI up to that point in time.

**QUESTION**: Which of the variables available on the ASIS portal would allow you to derive this information?

**QUESTION**: In case your growing season of interest is not covered by the Phenology indicator of the ASIS portal, how would you proceed in determining the impact of the drought on your growing season of interest?

### Step 6: Get population data

To get an idea how many people are directly affected by the drought, we can consult the [WPOP database](https://hub.worldpop.org/).

FAO provides access to parts of this database:

In [ ]:
from vito_agri_tutorials.fao.wpop import WPOP_SUPPORTED_VARIABLES
import pandas as pd

df_vars = pd.DataFrame.from_dict(WPOP_SUPPORTED_VARIABLES)
df_vars = df_vars.transpose()
df_vars

Let's download population count data for the selected states:

In [ ]:
from pathlib import Path
from vito_agri_tutorials.fao.wpop import extract_wpop_data

variable = "WPOP-T"

out_dir = Path('./results/2_wpop')
out_dir.mkdir(parents=True, exist_ok=True)

# WPOP data is only available between 2000 and 2020, we select the most recent year.
start_date = '2020-01-01'

wpop = extract_wpop_data(
    variable,
    gdf,
    out_dir,
    start_date,
    write_tif=True,
    debug=True,
)

Using the area statistics, we can compute the total number of people in the state:

In [ ]:
from vito_agri_tutorials.fao.wpop import compute_area_stats

wpop_stats = compute_area_stats(wpop)
wpop_stats

**QUESTION**: Now that you have both the MVHI data and population count data at pixel level, you could also compute the number of people living in the most severly affected locations of the state.<br>
How would you tackle this problem?